### ISSUE TITLE
Table for the simulation results

### ISSUE THREAD

**Issue by Kenkleinman** [katieleap/normanal#22]

**Comment by katieleap** [comment]
Number of simulations, number rejected, power, confidence limits (plus everything from the other table first (except calculated power)).

**Comment by Kenkleinman** [comment]
So, looking at the issue, I recall my thinking: The power alone is sometimes misleading, if you do a small number of replicates-- power of 90% on 10 simulations means you rejected 9 times-- big whoop.  The CI will help with that, but the # rejected is also good.  If there's room in the table, please do add, & sorry for the re-do.
