### ISSUE TITLE
Add a by-line, disclaimer, and (if it's not there yet) a license

### ISSUE THREAD

**Issue by Kenkleinman** [katieleap/normanal#5]
By-line is definitely both of us!!

**Comment by katieleap** [comment]
What should the text of the disclaimer be?

**Comment by Kenkleinman** [comment]
_We provide the calculations above as a service to the public.  We are not
responsible for, and expressly disclaim all liability for, damages of any
kind arising out of use, reference to, or reliance on any information
contained herein._

**Comment by Kenkleinman** [comment]
Disclaimer should be hidden in a link, just like the model equation

**Comment by Kenkleinman** [comment]
I did it!
