### ISSUE TITLE
Add a citations tab

### ISSUE THREAD

**Issue by Kenkleinman** [katieleap/normanal#6]
This is what it should contain:

For Normal results with constant cluster size:

Donner, A. and Klar, N. Statistical Considerations in the Design and Analysis of Community Intervention Trials. The Journal of Clinical Epidemiology 1996;49(4):435-439 PMID: 8621994

Murray D. Design and Analysis of Group-Randomized Trials. New York: Oxford University Press; 1998

For variable cluster size using the coefficient of variation:

Eldridge SM, Ashby D, Kerry S.  Sample size for cluster randomized trials: effect of coefficient of variation of cluster size and analysis method.   Int. J. Epidemiol. (October 2006) 35(5): 1292-1300.doi: 10.1093/ije/dyl129  PMID: 16943232

For simulations:

Reich NG, Myers JA, Obeng D, Milstone AM, Perl TM. Empirical Power and Sample Size Calculations for Cluster-Randomized and Cluster-Randomized Crossover Studies.  PLoS ONE 2012.7(4):e35564 doi: 10.1371/journal.pone.0035564 PMCID: PMC3338707

In addition, Katie, the Eldridge and Reich links could be hidden with, say, asterisks links, and revealed when clicked, like the model equation.

**Comment by katieleap** [comment]
Why do the links need to be hidden? And where?

**Comment by Kenkleinman** [comment]
Sorry, that was cryptic.  The Eldridge link could go in an asterisk on "Cluster size is variable".  The Reich one would be for the simulations, but I guess that would only make sense for the output area, as currently configured.  No need to do that if it's a hassle.  The tab I'm sure would be simple and is more important anyhow.

**Comment by Kenkleinman** [comment]
Forget the hidden links.
